# Generated by Django 5.1.7 on 2025-03-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS trips_customuser (
            id INT AUTO_INCREMENT PRIMARY KEY,
            password VARCHAR(128) NOT NULL,
            last_login DATETIME NULL,
            is_superuser TINYINT(1) NOT NULL,
            username VARCHAR(150) NOT NULL UNIQUE,
            first_name VARCHAR(150) NOT NULL,
            last_name VARCHAR(150) NOT NULL,
            email VARCHAR(254) NOT NULL,
            is_staff TINYINT(1) NOT NULL,
            is_active TINYINT(1) NOT NULL,
            date_joined DATETIME NOT NULL,
            profile_picture VARCHAR(100) NULL,
            is_driver TINYINT(1) NOT NULL DEFAULT 0
        );
            """,
            "DROP TABLE IF EXISTS trips_customuser;"
        ),
    ]