# Generated by Django 5.1.7 on 2025-03-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_dropoff_lat_trip_dropoff_lng_trip_pickup_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
