# Generated by Django 5.1.7 on 2025-03-28 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eldlog',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eld_logs', to='trips.trip'),
        ),
    ]
