# Generated by Django 5.1.7 on 2025-04-06 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_eldlog_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trucks', to=settings.AUTH_USER_MODEL),
        ),
    ]
